import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../../app/dependency_injection/app_providers.dart';
import '../../../app/localization/localization_extensions.dart';
import '../../../app/theme/app_tokens.dart';
import '../../../shared/models/demo_user_profile.dart';
import '../../../shared/enums/app_enums.dart';

class SplashPage extends StatelessWidget { const SplashPage({super.key}); @override Widget build(BuildContext context)=>Scaffold(body:AppLoadingIdentity(title:context.l10n.appName,label:context.l10n.loading)); }
class AppLoadingIdentity extends StatelessWidget { const AppLoadingIdentity({super.key,required this.title,required this.label}); final String title,label; @override Widget build(BuildContext context)=>Center(child:Column(mainAxisSize:MainAxisSize.min,children:[Icon(Icons.fact_check_outlined,size:64,color:Theme.of(context).colorScheme.primary),Text(title,style:Theme.of(context).textTheme.headlineSmall),const SizedBox(height:AppSpacing.medium),Semantics(label:label,child:const CircularProgressIndicator())])); }
class LanguageSelectionPage extends ConsumerWidget { const LanguageSelectionPage({super.key}); @override Widget build(BuildContext context,WidgetRef ref)=>Scaffold(body:SafeArea(child:Center(child:SingleChildScrollView(padding:const EdgeInsets.all(AppSpacing.large),child:ConstrainedBox(constraints:const BoxConstraints(maxWidth:520),child:Column(children:[Icon(Icons.translate,size:64,color:Theme.of(context).colorScheme.primary),Text(context.l10n.language,style:Theme.of(context).textTheme.headlineMedium),const SizedBox(height:AppSpacing.large),SegmentationLanguageSelector(locale:ref.watch(localeProvider),onChanged:(v)=>ref.read(localeProvider.notifier).state=v),const SizedBox(height:AppSpacing.large),FilledButton.icon(key:const Key('language-continue'),onPressed:()=>ref.read(sessionProvider.notifier).beginProfileSelection(),icon:const Icon(Icons.arrow_forward),label:Text(context.l10n.continueLabel))])))))); }
class SegmentationLanguageSelector extends StatelessWidget { const SegmentationLanguageSelector({super.key,required this.locale,required this.onChanged}); final Locale? locale; final ValueChanged<Locale> onChanged; @override Widget build(BuildContext context)=>SegmentedButton<String>(segments:[ButtonSegment(value:'ar',label:Text(context.l10n.arabic)),ButtonSegment(value:'en',label:Text(context.l10n.english))],selected:{locale?.languageCode??Localizations.localeOf(context).languageCode},onSelectionChanged:(v)=>onChanged(Locale(v.first)) ); }
class DemoLoginPage extends ConsumerWidget { const DemoLoginPage({super.key}); @override Widget build(BuildContext context,WidgetRef ref)=>Scaffold(appBar:AppBar(title:Text(context.l10n.appName),actions:[IconButton(onPressed:()=>ref.read(localeProvider.notifier).state=Locale(Localizations.localeOf(context).languageCode=='ar'?'en':'ar'),icon:const Icon(Icons.translate),tooltip:context.l10n.language)]),body:SafeArea(child:ListView(padding:const EdgeInsets.all(AppSpacing.medium),children:[if(ref.watch(sessionProvider).status==AuthenticationStatus.expired)Card(color:Theme.of(context).colorScheme.errorContainer,child:Padding(padding:const EdgeInsets.all(AppSpacing.medium),child:Text(context.l10n.sessionExpired))),Text(context.l10n.authenticationSimulated),const SizedBox(height:AppSpacing.medium),TextField(decoration:InputDecoration(labelText:context.l10n.username)),const SizedBox(height:AppSpacing.small),TextField(obscureText:true,decoration:InputDecoration(labelText:context.l10n.password)),const SizedBox(height:AppSpacing.small),FilledButton(onPressed:()=>ref.read(sessionProvider.notifier).beginProfileSelection(),child:Text(context.l10n.login)),const SizedBox(height:AppSpacing.large),Text(context.l10n.selectDemoProfile,style:Theme.of(context).textTheme.titleLarge),for(final p in demoProfiles)DemoProfileCard(profile:p,onSelected:()=>ref.read(sessionProvider.notifier).authenticate(p))]))); }
class DemoProfileCard extends StatelessWidget { const DemoProfileCard({super.key,required this.profile,required this.onSelected}); final DemoUserProfile profile; final VoidCallback onSelected; @override Widget build(BuildContext context){final lang=Localizations.localeOf(context).languageCode; return Card(key:Key('profile-${profile.id}'),margin:const EdgeInsets.only(top:AppSpacing.small),child:ListTile(leading:CircleAvatar(child:Text(profile.avatarInitials)),title:Text(profile.localizedName(lang)),subtitle:Text(profile.localizedDepartment(lang)),trailing:const Icon(Icons.login),onTap:onSelected));} }
