import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../../app/dependency_injection/app_providers.dart';
import '../../../app/localization/localization_extensions.dart';
import '../../../app/theme/app_tokens.dart';
import '../../../shared/enums/app_enums.dart';
import '../../authentication/presentation/authentication_pages.dart';
import '../../home/presentation/home_page.dart';

class ProfilePage extends ConsumerWidget { const ProfilePage({super.key,required this.openGallery}); final VoidCallback openGallery; @override Widget build(BuildContext context,WidgetRef ref){final p=ref.watch(currentDemoProfileProvider)!; final lang=Localizations.localeOf(context).languageCode; return ListView(padding:const EdgeInsets.all(AppSpacing.medium),children:[ListTile(leading:CircleAvatar(child:Text(p.avatarInitials)),title:Text(p.localizedName(lang)),subtitle:Text('${roleLabel(context,p.role)} • ${p.localizedDepartment(lang)}')),Text(context.l10n.language,style:Theme.of(context).textTheme.titleMedium),SegmentationLanguageSelector(locale:ref.watch(localeProvider),onChanged:(v)=>ref.read(localeProvider.notifier).state=v),const SizedBox(height:AppSpacing.medium),Text(context.l10n.theme,style:Theme.of(context).textTheme.titleMedium),ThemeModeSelector(value:ref.watch(themeModeProvider),onChanged:(v)=>ref.read(themeModeProvider.notifier).state=v),const SizedBox(height:AppSpacing.medium),Text(context.l10n.connectivity,style:Theme.of(context).textTheme.titleMedium),ConnectivitySelector(value:ref.watch(connectivityProvider),onChanged:(v)=>ref.read(connectivityProvider.notifier).state=v),const Divider(height:AppSpacing.xLarge),ListTile(leading:const Icon(Icons.palette_outlined),title:Text(context.l10n.foundationGallery),onTap:openGallery),ListTile(leading:const Icon(Icons.switch_account),title:Text(context.l10n.switchProfile),onTap:()=>ref.read(sessionProvider.notifier).beginProfileSelection()),ListTile(key:const Key('expire-session'),leading:const Icon(Icons.timer_off_outlined),title:Text(context.l10n.expireSession),onTap:()=>ref.read(sessionProvider.notifier).expire()),ListTile(key:const Key('logout'),leading:const Icon(Icons.logout),title:Text(context.l10n.logout),onTap:()=>ref.read(sessionProvider.notifier).logout()),Center(child:Chip(label:Text('${context.l10n.demoMode} • 1.0.0')))]); } }
class ThemeModeSelector extends StatelessWidget { const ThemeModeSelector({super.key,required this.value,required this.onChanged});final ThemeMode value;final ValueChanged<ThemeMode> onChanged; @override Widget build(BuildContext context)=>DropdownButtonFormField<ThemeMode>(value:value,items:[DropdownMenuItem(value:ThemeMode.light,child:Text(context.l10n.light)),DropdownMenuItem(value:ThemeMode.dark,child:Text(context.l10n.dark)),DropdownMenuItem(value:ThemeMode.system,child:Text(context.l10n.systemDefault))],onChanged:(v){if(v!=null)onChanged(v);}); }
class ConnectivitySelector extends StatelessWidget { const ConnectivitySelector({super.key,required this.value,required this.onChanged});final SimulatedConnectivityStatus value;final ValueChanged<SimulatedConnectivityStatus> onChanged; @override Widget build(BuildContext context)=>SegmentedButton<SimulatedConnectivityStatus>(segments:[ButtonSegment(value:SimulatedConnectivityStatus.online,label:Text(context.l10n.online),icon:const Icon(Icons.cloud_done_outlined)),ButtonSegment(value:SimulatedConnectivityStatus.offline,label:Text(context.l10n.offline),icon:const Icon(Icons.cloud_off_outlined)),ButtonSegment(value:SimulatedConnectivityStatus.unstable,label:Text(context.l10n.unstableConnection),icon:const Icon(Icons.warning_amber))],selected:{value},onSelectionChanged:(v)=>onChanged(v.first)); }
