import 'package:flutter_test/flutter_test.dart';
import 'package:organization_task_manager/core/demo/demo_data_store.dart';
import 'package:organization_task_manager/core/demo/demo_seed_ids.dart';
import 'package:organization_task_manager/core/demo/in_memory_repositories.dart';
import 'package:organization_task_manager/core/domain/authorization_models.dart';
import 'package:organization_task_manager/core/domain/domain_enums.dart';
import 'package:organization_task_manager/core/domain/entities.dart';
import 'package:organization_task_manager/features/organization/data/repository_authorization_service.dart';
import 'package:organization_task_manager/features/organization/data/repository_organization_hierarchy_service.dart';

void main(){
 late DemoDataStore store; late RepositoryAuthorizationService auth;
 setUp(() { store=DemoDataStore(); final users=InMemoryUserRepository(store);final organization=InMemoryOrganizationRepository(store);auth=RepositoryAuthorizationService(users:users,organization:organization,hierarchy:RepositoryOrganizationHierarchyService(users:users,organization:organization),overrides:InMemoryPermissionOverrideRepository(store)); });
 test('approved role matrix keeps administrative and executive power separate',() async {expect(await auth.hasPermission(DemoSeedIds.ahmed,PermissionCode.taskCreateSelf),isTrue);expect(await auth.hasPermission(DemoSeedIds.ahmed,PermissionCode.taskCreateForOthers),isFalse);expect(await auth.hasPermission(DemoSeedIds.sara,PermissionCode.taskAssignOrganization),isTrue);expect(await auth.hasPermission(DemoSeedIds.sara,PermissionCode.taskReassignOrganization),isTrue);expect(await auth.hasPermission(DemoSeedIds.sara,PermissionCode.reportViewEmployeePerformance),isTrue);expect(await auth.hasPermission(DemoSeedIds.omar,PermissionCode.reportViewOrganization),isTrue);expect(await auth.hasPermission(DemoSeedIds.omar,PermissionCode.adminView),isFalse);expect(await auth.hasPermission(DemoSeedIds.laila,PermissionCode.adminView),isTrue);expect(await auth.hasPermission(DemoSeedIds.laila,PermissionCode.reportViewOrganization),isFalse);expect(await auth.hasPermission(DemoSeedIds.laila,PermissionCode.taskApprove),isFalse);});
 test('queue permissions are membership and target scoped',() async {final support=const AccessTarget(teamId:DemoSeedIds.technicalSupportQueue);final other=const AccessTarget(teamId:DemoSeedIds.applicationSupport);expect((await auth.check(userId:DemoSeedIds.khaled,permission:PermissionCode.taskClaimTeamQueue,target:support)).allowed,isTrue);expect((await auth.check(userId:DemoSeedIds.khaled,permission:PermissionCode.taskClaimTeamQueue,target:other)).allowed,isFalse);expect(await auth.hasPermission(DemoSeedIds.ahmed,PermissionCode.taskClaimTeamQueue),isFalse);});
 test('deny wins, allow adds permission, and scope remains enforced',() async {store.permissionOverrides.addAll([const PermissionOverride(userId:DemoSeedIds.sara,permissionCode:PermissionCode.taskApprove,effect:PermissionOverrideEffect.deny,reason:'demo deny'),const PermissionOverride(userId:DemoSeedIds.ahmed,permissionCode:PermissionCode.taskCreateForOthers,effect:PermissionOverrideEffect.allow,reason:'demo allow')]);expect(await auth.hasPermission(DemoSeedIds.sara,PermissionCode.taskApprove),isFalse);expect(await auth.hasPermission(DemoSeedIds.ahmed,PermissionCode.taskCreateForOthers),isTrue);final decision=await auth.check(userId:DemoSeedIds.ahmed,permission:PermissionCode.taskCreateForOthers,target:const AccessTarget(departmentId:DemoSeedIds.finance));expect(decision.reasonCode,AuthorizationReasonCode.insufficientScope);});
 test('confidentiality and organization boundaries fail closed',() async {expect((await auth.check(userId:DemoSeedIds.ahmed,permission:PermissionCode.taskViewOwn,target:const AccessTarget(organizationId:'other',confidentialityCode:ConfidentialityCode.internal))).allowed,isFalse);expect((await auth.check(userId:DemoSeedIds.ahmed,permission:PermissionCode.taskViewOwn,target:const AccessTarget(confidentialityCode:ConfidentialityCode.confidential))).allowed,isFalse);expect((await auth.check(userId:DemoSeedIds.ahmed,permission:PermissionCode.taskViewOwn,target:const AccessTarget(confidentialityCode:ConfidentialityCode.restricted))).allowed,isFalse);});
 test('unknown permission, role and user fail closed',() async {expect(await auth.hasPermission('missing',PermissionCode.profileViewSelf),isFalse);expect(await auth.hasPermission(DemoSeedIds.ahmed,PermissionCode.unknown),isFalse);final user=store.users.first;store.users[0]=OrganizationUser(id:user.id,employeeNumber:user.employeeNumber,nameAr:user.nameAr,departmentId:user.departmentId,roleId:'missing',status:user.status);expect(await auth.hasPermission(user.id,PermissionCode.profileViewSelf),isFalse);});
}
