import '../../core/domain/entities.dart';
import '../../core/domain/domain_enums.dart';
abstract interface class UserRepository { Future<OrganizationUser?> getUserById(String id); Future<List<OrganizationUser>> getUsers(); Future<List<OrganizationUser>> getUsersByDepartment(String id); Future<List<OrganizationUser>> getDirectReports(String managerId); Future<List<OrganizationUser>> getUsersByTeam(String teamId); }
abstract interface class OrganizationRepository { Future<List<Department>> getDepartments(); Future<Department?> getDepartmentById(String id); Future<List<Team>> getTeams(); Future<List<Team>> getTeamsByDepartment(String id); Future<List<TeamMembership>> getTeamMembers(String teamId); }
abstract interface class TaskRepository { Future<Task?> getTaskById(String id); Future<List<Task>> getTasks(); Future<List<Task>> getTasksForUser(String id); Future<List<Task>> getTasksForTeam(String id); Future<List<Task>> getSubtasks(String id); Future<List<TaskAssignment>> getTaskAssignments(String id); Future<List<ChecklistItem>> getChecklistItems(String id); Future<List<TaskComment>> getComments(String id); Future<List<TaskAttachment>> getAttachments(String id); Future<void> insertTaskRecord(Task task); Future<void> updateTaskRecord(Task task); Future<void> insertAssignments(List<TaskAssignment> values); Future<void> insertChecklistItems(List<ChecklistItem> values); }
abstract interface class TaskConfigurationRepository { Future<List<TaskPriority>> getPriorities(); Future<List<TaskCategory>> getCategories(); Future<List<ConfidentialityLevel>> getConfidentialityLevels(); Future<List<ApprovalRule>> getApprovalRules(); Future<List<EscalationRule>> getEscalationRules(); Future<List<TaskTemplate>> getTaskTemplates(); }
abstract interface class NotificationRepository { Future<List<AppNotification>> getNotificationsForUser(String id); Future<int> getUnreadCount(String id); }
abstract interface class AuditRepository { Future<List<AuditEvent>> getAuditEvents(); Future<List<AuditEvent>> getAuditEventsForTask(String id); Future<void> appendAuditEvent(AuditEvent event); }
abstract interface class SyncRepository { Future<List<SyncOperation>> getPendingOperations(); Future<void> appendOperation(SyncOperation operation); Future<void> updateOperationStatus(String id,SyncOperationStatus status); }
abstract interface class SettingsRepository { Future<String?> getSetting(String key); Future<void> saveSetting(String key,String value); Future<void> removeSetting(String key); }
