import 'dart:async';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import '../../../app/dependency_injection/app_providers.dart';
import '../../../app/localization/localization_extensions.dart';
import '../../../core/domain/domain_enums.dart';
import '../../../core/widgets/foundation_views.dart';
import '../domain/task_query_models.dart';
import 'task_presentation.dart';
import 'task_providers.dart';
import 'task_widgets.dart';

class TaskListPage extends ConsumerStatefulWidget {
 const TaskListPage({super.key,this.pageContext=const TaskPageContext(TaskPageKind.generic)}); final TaskPageContext pageContext;
 @override ConsumerState<TaskListPage> createState()=>_TaskListPageState();
}
class _TaskListPageState extends ConsumerState<TaskListPage>{
 Timer? _debounce; late final TextEditingController _search;
 @override void initState(){super.initState();_search=TextEditingController();Future.microtask((){if(mounted)ref.read(currentTaskQueryProvider.notifier).state=widget.pageContext.initialQuery;});}
 @override void dispose(){_debounce?.cancel();_search.dispose();super.dispose();}
 @override Widget build(BuildContext context){final async=ref.watch(taskQueryResultProvider);final query=ref.watch(currentTaskQueryProvider);final permissions=ref.watch(currentEffectivePermissionsProvider).valueOrNull??const <PermissionCode>{};final canCreate=permissions.contains(PermissionCode.taskCreateSelf)||permissions.contains(PermissionCode.taskCreateForOthers);return Scaffold(floatingActionButton:canCreate?FloatingActionButton.extended(onPressed:()=>context.push('/tasks/create'),icon:const Icon(Icons.add_task),label:Text(context.l10n.createTask)):null,body:SafeArea(child:Column(children:[
  Padding(padding:const EdgeInsets.fromLTRB(12,8,12,4),child:Row(crossAxisAlignment:CrossAxisAlignment.end,children:[Expanded(child:Text(widget.pageContext.title(context),style:Theme.of(context).textTheme.headlineSmall?.copyWith(fontWeight:FontWeight.bold))),async.valueOrNull==null?const SizedBox.shrink():Text(TaskPresentation.text(context,'${async.value!.items.length} results','${async.value!.items.length} نتيجة'),style:Theme.of(context).textTheme.labelMedium)])),
  if(widget.pageContext.isCritical)Padding(padding:const EdgeInsets.symmetric(horizontal:12,vertical:2),child:Align(alignment:AlignmentDirectional.centerStart,child:Text(TaskPresentation.text(context,'Urgent, overdue, blocked, and approval-sensitive tasks.','المهام العاجلة والمتأخرة والمتوقفة والمنتظرة للاعتماد.'),style:Theme.of(context).textTheme.bodySmall))),
  if(widget.pageContext.showsScope)_ScopeSelector(query:query),
  Padding(padding:const EdgeInsets.fromLTRB(12,5,12,5),child:Row(children:[Expanded(child:SizedBox(height:42,child:TextField(controller:_search,textInputAction:TextInputAction.search,decoration:InputDecoration(isDense:true,prefixIcon:const Icon(Icons.search,size:20),hintText:widget.pageContext.searchHint(context),suffixIcon:query.searchText.isEmpty?null:IconButton(icon:const Icon(Icons.clear,size:18),onPressed:(){_search.clear();_set(query.copyWith(searchText:''));})),onChanged:(v){_debounce?.cancel();_debounce=Timer(const Duration(milliseconds:300),()=>_set(ref.read(currentTaskQueryProvider).copyWith(searchText:v)));}))),
   _HeaderButton(icon:Icons.filter_list,label:context.l10n.filters,badge:query.activeFilterCount,onPressed:()=>_showFilters(context,query)),
   _HeaderButton(icon:Icons.sort,label:context.l10n.sort,onPressed:()=>_showSort(context,query)),
   _HeaderButton(icon:Icons.bookmarks_outlined,label:context.l10n.savedFilters,onPressed:()=>_showSaved(context,query))])),
  SizedBox(height:38,child:ListView(scrollDirection:Axis.horizontal,padding:const EdgeInsetsDirectional.only(start:12,end:12),children:[for(final view in TaskListView.values.where((v)=>v!=TaskListView.critical))Padding(padding:const EdgeInsetsDirectional.only(end:6),child:ChoiceChip(visualDensity:VisualDensity.compact,labelPadding:const EdgeInsets.symmetric(horizontal:3),label:Text(TaskPresentation.view(context,view),style:Theme.of(context).textTheme.labelSmall),selected:query.view==view,onSelected:(_)=>_set(query.copyWith(view:view))) )])),
  Expanded(child:async.when(loading:()=>const Center(child:CircularProgressIndicator()),error:(e,s)=>AppErrorView(label:context.l10n.somethingWentWrong,retryLabel:context.l10n.retry,onRetry:()=>ref.invalidate(taskQueryResultProvider)),data:(result){if(result==null)return const SizedBox.shrink();if(result.items.isEmpty)return Center(child:Text(context.l10n.noTasksMatchFilters));return RefreshIndicator(onRefresh:()async=>ref.invalidate(taskQueryResultProvider),child:LayoutBuilder(builder:(context,c){final columns=c.maxWidth>=700?2:1;return GridView.builder(padding:const EdgeInsets.all(12),gridDelegate:SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount:columns,mainAxisExtent:185,crossAxisSpacing:10,mainAxisSpacing:10),itemCount:result.items.length,itemBuilder:(c,i)=>TaskCard(item:result.items[i],now:result.generatedAt,onTap:()=>context.push('/tasks/${result.items[i].task.id}')));}));}))])));
 }
 void _set(TaskQuery q)=>ref.read(currentTaskQueryProvider.notifier).state=q;
 Future<void> _showFilters(BuildContext context,TaskQuery query)async{final value=await showModalBottomSheet<TaskQuery>(context:context,isScrollControlled:true,useSafeArea:true,builder:(c)=>_FilterSheet(initial:query));if(value!=null)_set(value);}
 Future<void> _showSort(BuildContext context,TaskQuery query)async{final value=await showModalBottomSheet<TaskQuery>(context:context,useSafeArea:true,builder:(c)=>_SortSheet(initial:query));if(value!=null)_set(value);}
 Future<void> _showSaved(BuildContext context,TaskQuery query)async{await showModalBottomSheet<void>(context:context,isScrollControlled:true,useSafeArea:true,builder:(c)=>_SavedFiltersSheet(current:query));if(mounted)ref.invalidate(savedTaskFiltersProvider);}
}

class _HeaderButton extends StatelessWidget{const _HeaderButton({required this.icon,required this.label,required this.onPressed,this.badge=0});final IconData icon;final String label;final VoidCallback onPressed;final int badge;
 @override Widget build(BuildContext c)=>Semantics(label:label,button:true,child:Stack(children:[IconButton(visualDensity:VisualDensity.compact,tooltip:label,icon:Icon(icon,size:21),onPressed:onPressed),if(badge>0)PositionedDirectional(end:2,top:1,child:Badge(label:Text('$badge')))]));}
class _ScopeSelector extends ConsumerWidget{const _ScopeSelector({required this.query});final TaskQuery query;@override Widget build(BuildContext context,WidgetRef ref){final permitted=ref.watch(permittedTaskScopesProvider).valueOrNull??const {TaskQueryScope.self};return SizedBox(height:38,child:ListView(scrollDirection:Axis.horizontal,padding:const EdgeInsets.symmetric(horizontal:12),children:[for(final scope in TaskQueryScope.values.where(permitted.contains))Padding(padding:const EdgeInsetsDirectional.only(end:5),child:ChoiceChip(visualDensity:VisualDensity.compact,label:Text(TaskPresentation.scope(context,scope)),selected:query.scope==scope,onSelected:(_)=>ref.read(currentTaskQueryProvider.notifier).state=query.copyWith(scope:scope)))]));}}

class _FilterSheet extends StatefulWidget{const _FilterSheet({required this.initial});final TaskQuery initial;@override State<_FilterSheet> createState()=>_FilterSheetState();}
class _FilterSheetState extends State<_FilterSheet>{late TaskQuery q;@override void initState(){super.initState();q=widget.initial;}
 @override Widget build(BuildContext context)=>DraggableScrollableSheet(expand:false,initialChildSize:.92,minChildSize:.55,maxChildSize:.98,builder:(c,controller)=>Column(children:[ListTile(title:Text(context.l10n.filters,style:Theme.of(context).textTheme.titleLarge),subtitle:Text(TaskPresentation.text(context,'${q.activeFilterCount} active filters','${q.activeFilterCount} عوامل نشطة')),trailing:IconButton(icon:const Icon(Icons.close),onPressed:()=>Navigator.pop(context))),Expanded(child:ListView(controller:controller,padding:const EdgeInsets.symmetric(horizontal:12),children:[
  _section(TaskPresentation.text(context,'Status','الحالة'),Wrap(spacing:5,children:[for(final s in TaskStatus.values.where((s)=>s!=TaskStatus.unknown))FilterChip(label:Text(TaskPresentation.status(context,s)),selected:q.statuses.contains(s),onSelected:(v)=>setState(()=>q=q.copyWith(statuses:{...q.statuses}..removeWhere((x)=>x==s)..addAll(v?[s]:[]))))])),
  _section(TaskPresentation.text(context,'Priority','الأولوية'),Wrap(spacing:5,children:[for(final p in ['low','normal','high','urgent','critical'])FilterChip(label:Text(TaskPresentation.priority(context,p)),selected:q.priorities.contains(p),onSelected:(v)=>setState(()=>q=q.copyWith(priorities:{...q.priorities}..remove(p)..addAll(v?[p]:[]))))])),
  _dateSection(context),
  for(final label in ['Creator','Owner','Contributor','Team','Department','Category'])_section(TaskPresentation.text(context,label,switch(label){'Creator'=>'المنشئ','Owner'=>'المسؤول','Contributor'=>'المساهم','Team'=>'الفريق','Department'=>'الإدارة',_=>'الفئة'}),Text(TaskPresentation.text(context,'Use search and organizational scope to narrow this value.','استخدم البحث والنطاق المؤسسي لتضييق هذه القيمة.'),style:Theme.of(context).textTheme.bodySmall)),
  _section(TaskPresentation.text(context,'Assignment mode','نمط الإسناد'),Wrap(spacing:5,children:[for(final m in AssignmentMode.values.where((x)=>x!=AssignmentMode.unknown))FilterChip(label:Text(TaskPresentation.assignmentMode(context,m)),selected:q.assignmentModes.contains(m),onSelected:(v)=>setState(()=>q=q.copyWith(assignmentModes:{...q.assignmentModes}..remove(m)..addAll(v?[m]:[]))))])),
  _section(TaskPresentation.text(context,'Approval status','حالة الاعتماد'),Wrap(spacing:5,children:[for(final a in ApprovalStatus.values.where((x)=>x!=ApprovalStatus.unknown))FilterChip(label:Text(TaskPresentation.approval(context,a)),selected:q.approvalStatuses.contains(a),onSelected:(v)=>setState(()=>q=q.copyWith(approvalStatuses:{...q.approvalStatuses}..remove(a)..addAll(v?[a]:[]))))])),
  _section(TaskPresentation.text(context,'Confidentiality','السرية'),Wrap(spacing:5,children:[for(final x in ['public','internal','confidential','restricted'])FilterChip(label:Text(TaskPresentation.confidentiality(context,x)),selected:q.confidentialityLevels.contains(x),onSelected:(v)=>setState(()=>q=q.copyWith(confidentialityLevels:{...q.confidentialityLevels}..remove(x)..addAll(v?[x]:[]))))])),
  _boolean('Blocked','متوقفة',q.blockedState,(v)=>q=q.copyWith(blockedState:v)),_boolean('Recurring','متكررة',q.recurringState,(v)=>q=q.copyWith(recurringState:v)),_boolean('Locally modified','معدلة محلياً',q.locallyModifiedState,(v)=>q=q.copyWith(locallyModifiedState:v)),_boolean('Pending synchronization','بانتظار المزامنة',q.pendingSynchronizationState,(v)=>q=q.copyWith(pendingSynchronizationState:v)),const SizedBox(height:12)])),
  Padding(padding:const EdgeInsets.all(12),child:Row(children:[TextButton(onPressed:()=>setState(()=>q=TaskQuery(view:q.view,scope:q.scope,searchText:q.searchText)),child:Text(context.l10n.resetFilters)),const Spacer(),TextButton(onPressed:()=>Navigator.pop(context),child:Text(context.l10n.cancel)),const SizedBox(width:8),FilledButton(onPressed:()=>Navigator.pop(context,q),child:Text(context.l10n.applyFilters))]))]));
 Widget _section(String title,Widget child)=>ExpansionTile(tilePadding:EdgeInsets.zero,title:Text(title),children:[Align(alignment:AlignmentDirectional.centerStart,child:child),const SizedBox(height:7)]);
 Widget _boolean(String en,String ar,TaskBooleanFilter value,void Function(TaskBooleanFilter) set)=>_section(TaskPresentation.text(context,en,ar),SegmentedButton<TaskBooleanFilter>(showSelectedIcon:false,segments:[for(final x in TaskBooleanFilter.values)ButtonSegment(value:x,label:Text(TaskPresentation.text(context,switch(x){TaskBooleanFilter.any=>'Any',TaskBooleanFilter.yes=>'Yes',TaskBooleanFilter.no=>'No'},switch(x){TaskBooleanFilter.any=>'الكل',TaskBooleanFilter.yes=>'نعم',TaskBooleanFilter.no=>'لا'})))],selected:{value},onSelectionChanged:(v)=>setState(()=>set(v.first))));
 Widget _dateSection(BuildContext c)=>_section(TaskPresentation.text(c,'Date ranges','نطاقات التاريخ'),Wrap(spacing:8,runSpacing:8,children:[OutlinedButton.icon(icon:const Icon(Icons.event),label:Text(TaskPresentation.text(c,'Due-date range','نطاق الاستحقاق')),onPressed:()async{final r=await showDateRangePicker(context:c,firstDate:DateTime(2020),lastDate:DateTime(2035));if(r!=null)setState(()=>q=q.copyWith(dueDateFrom:r.start,dueDateTo:r.end));}),OutlinedButton.icon(icon:const Icon(Icons.today),label:Text(TaskPresentation.text(c,'Creation-date range','نطاق الإنشاء')),onPressed:()async{final r=await showDateRangePicker(context:c,firstDate:DateTime(2020),lastDate:DateTime(2035));if(r!=null)setState(()=>q=q.copyWith(creationDateFrom:r.start,creationDateTo:r.end));})]));
}

class _SortSheet extends StatefulWidget{const _SortSheet({required this.initial});final TaskQuery initial;@override State<_SortSheet> createState()=>_SortSheetState();}
class _SortSheetState extends State<_SortSheet>{late TaskSortField field=widget.initial.sortField;late SortDirection direction=widget.initial.sortDirection;
 @override Widget build(BuildContext context)=>SafeArea(child:Column(mainAxisSize:MainAxisSize.min,children:[ListTile(title:Text(context.l10n.sort,style:Theme.of(context).textTheme.titleLarge)),Flexible(child:SingleChildScrollView(child:RadioGroup<TaskSortField>(groupValue:field,onChanged:(v)=>setState(()=>field=v!),child:Column(children:[for(final f in TaskSortField.values)RadioListTile(value:f,dense:true,title:Text(_label(context,f)))]))),),Padding(padding:const EdgeInsets.symmetric(horizontal:16),child:SegmentedButton<SortDirection>(segments:[ButtonSegment(value:SortDirection.ascending,label:Text(TaskPresentation.text(context,'Ascending','تصاعدي')),icon:const Icon(Icons.arrow_upward)),ButtonSegment(value:SortDirection.descending,label:Text(TaskPresentation.text(context,'Descending','تنازلي')),icon:const Icon(Icons.arrow_downward))],selected:{direction},onSelectionChanged:(v)=>setState(()=>direction=v.first))),Padding(padding:const EdgeInsets.all(16),child:SizedBox(width:double.infinity,child:FilledButton(onPressed:()=>Navigator.pop(context,widget.initial.copyWith(sortField:field,sortDirection:direction)),child:Text(context.l10n.applyFilters))))]));
 String _label(BuildContext c,TaskSortField f)=>TaskPresentation.text(c,switch(f){TaskSortField.dueDate=>'Due date',TaskSortField.priority=>'Priority',TaskSortField.creationDate=>'Creation date',TaskSortField.lastUpdate=>'Last updated',TaskSortField.progress=>'Progress',TaskSortField.estimatedEffort=>'Estimated effort',TaskSortField.taskNumber=>'Task number'},switch(f){TaskSortField.dueDate=>'تاريخ الاستحقاق',TaskSortField.priority=>'الأولوية',TaskSortField.creationDate=>'تاريخ الإنشاء',TaskSortField.lastUpdate=>'آخر تحديث',TaskSortField.progress=>'التقدم',TaskSortField.estimatedEffort=>'الجهد المقدر',TaskSortField.taskNumber=>'رقم المهمة'});
}

class _SavedFiltersSheet extends ConsumerWidget{const _SavedFiltersSheet({required this.current});final TaskQuery current;
 List<TaskSavedFilter> _presets(BuildContext c)=>[TaskSavedFilter(id:'preset-active',name:TaskPresentation.text(c,'My Active Tasks','مهامي النشطة'),query:TaskQuery(scope:TaskQueryScope.self,statuses:{TaskStatus.assigned,TaskStatus.inProgress}),isPreset:true),TaskSavedFilter(id:'preset-week',name:TaskPresentation.text(c,'Due This Week','مستحقة هذا الأسبوع'),query:TaskQuery(view:TaskListView.thisWeek),isPreset:true),TaskSavedFilter(id:'preset-high',name:TaskPresentation.text(c,'High Priority','أولوية عالية'),query:TaskQuery(priorities:{'high','urgent','critical'}),isPreset:true),TaskSavedFilter(id:'preset-approval',name:TaskPresentation.text(c,'Awaiting Approval','بانتظار الاعتماد'),query:TaskQuery(view:TaskListView.awaitingApproval),isPreset:true),TaskSavedFilter(id:'preset-blocked',name:TaskPresentation.text(c,'Blocked Tasks','المهام المتوقفة'),query:TaskQuery(view:TaskListView.blocked),isPreset:true)];
 @override Widget build(BuildContext context,WidgetRef ref){final saved=ref.watch(savedTaskFiltersProvider);return DraggableScrollableSheet(expand:false,initialChildSize:.78,maxChildSize:.95,builder:(c,controller)=>Column(children:[ListTile(title:Text(context.l10n.savedFilters,style:Theme.of(context).textTheme.titleLarge),trailing:IconButton(icon:const Icon(Icons.close),onPressed:()=>Navigator.pop(context))),Padding(padding:const EdgeInsets.symmetric(horizontal:16),child:Text(TaskPresentation.text(context,'Saved filters are available only during this app session.','عوامل التصفية المحفوظة متاحة خلال جلسة التطبيق الحالية فقط.'),style:Theme.of(context).textTheme.bodySmall)),Expanded(child:ListView(controller:controller,children:[for(final f in _presets(context))_tile(context,ref,f),...saved.when(data:(x)=>x.map((f)=>_tile(context,ref,f)),loading:()=>[const Center(child:CircularProgressIndicator())],error:(e,s)=>[Text(context.l10n.somethingWentWrong)])])),Padding(padding:const EdgeInsets.all(16),child:SizedBox(width:double.infinity,child:FilledButton.icon(icon:const Icon(Icons.add),label:Text(context.l10n.saveFilter),onPressed:()=>_save(context,ref))))]));}
 Widget _tile(BuildContext c,WidgetRef ref,TaskSavedFilter f)=>ListTile(leading:Icon(f.isDefault?Icons.star:Icons.bookmark_outline),title:Text(f.name),subtitle:f.isPreset?Text(TaskPresentation.text(c,'Preset','إعداد مسبق')):null,onTap:(){ref.read(currentTaskQueryProvider.notifier).state=f.query;Navigator.pop(c);},trailing:f.isPreset?null:PopupMenuButton<String>(onSelected:(v)async{final user=ref.read(currentOrganizationUserProvider);if(user==null)return;final service=ref.read(taskQueryServiceProvider);if(v=='default')await service.setDefaultFilter(userId:user.id,filterId:f.id);else await service.deleteSavedFilter(userId:user.id,filterId:f.id);ref.invalidate(savedTaskFiltersProvider);},itemBuilder:(c)=>[PopupMenuItem(value:'default',child:Text(TaskPresentation.text(c,'Set as default','تعيين كافتراضي'))),PopupMenuItem(value:'delete',child:Text(c.l10n.deleteSavedFilter))]));
 Future<void> _save(BuildContext context,WidgetRef ref)async{final controller=TextEditingController();final name=await showDialog<String>(context:context,builder:(c)=>AlertDialog(title:Text(context.l10n.saveFilter),content:TextField(controller:controller,autofocus:true,decoration:InputDecoration(labelText:context.l10n.filterName)),actions:[TextButton(onPressed:()=>Navigator.pop(c),child:Text(context.l10n.cancel)),FilledButton(onPressed:()=>Navigator.pop(c,controller.text.trim()),child:Text(context.l10n.saveFilter))]));controller.dispose();if(name==null)return;if(name.isEmpty){if(context.mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(TaskPresentation.text(context,'Enter a filter name.','أدخل اسماً لعامل التصفية.'))));return;}final user=ref.read(currentOrganizationUserProvider);if(user==null)return;await ref.read(taskQueryServiceProvider).saveFilter(userId:user.id,filter:TaskSavedFilter(id:'filter-${DateTime.now().microsecondsSinceEpoch}',name:name,query:current));ref.invalidate(savedTaskFiltersProvider);}
}

class TaskDetailsPage extends ConsumerWidget {const TaskDetailsPage({super.key,required this.taskId});final String taskId;
 @override Widget build(BuildContext context,WidgetRef ref){final async=ref.watch(taskDetailsProvider(taskId));return Scaffold(appBar:AppBar(title:Text(context.l10n.taskDetails)),body:async.when(loading:()=>const Center(child:CircularProgressIndicator()),error:(e,s)=>AppErrorView(label:context.l10n.somethingWentWrong,retryLabel:context.l10n.retry,onRetry:()=>ref.invalidate(taskDetailsProvider(taskId))),data:(d){if(d==null)return Center(child:Text(context.l10n.accessDenied));final ar=Localizations.localeOf(context).languageCode=='ar';final t=d.task;return LayoutBuilder(builder:(c,constraints)=>ListView(padding:EdgeInsets.symmetric(horizontal:constraints.maxWidth>800?(constraints.maxWidth-760)/2:12,vertical:10),children:[
  _section(context,null,Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(t.taskNumber,style:Theme.of(context).textTheme.labelLarge),const SizedBox(height:5),Text(ar?t.titleAr:(t.titleEn??t.titleAr),style:Theme.of(context).textTheme.titleLarge?.copyWith(fontWeight:FontWeight.bold)),const SizedBox(height:8),Wrap(spacing:6,runSpacing:6,children:[TaskStatusBadge(t.status),TaskPriorityBadge(d.priority),TaskConfidentialityBadge(d.confidentiality?.code),TaskSyncBadge(t.syncState)])])),
  _section(context,TaskPresentation.text(context,'Description','وصف المهمة'),Text(ar?t.descriptionAr:(t.descriptionEn??t.descriptionAr))),
  _section(context,TaskPresentation.text(context,'Assignment','الإسناد'),TaskAssignmentSummary(details:d)),
  _section(context,TaskPresentation.text(context,'Dates and planning','التواريخ والتخطيط'),Column(children:[_row(context,TaskPresentation.text(context,'Created date','تاريخ الإنشاء'),_date(context,t.createdAt)),_row(context,context.l10n.plannedStart,_date(context,t.plannedStartDate)),_row(context,context.l10n.dueDate,_date(context,t.dueDate)),_row(context,context.l10n.estimatedEffort,t.estimatedEffortMinutes==null?'—':TaskPresentation.text(context,'${t.estimatedEffortMinutes} minutes','${t.estimatedEffortMinutes} دقيقة')),_row(context,TaskPresentation.text(context,'Recurrence','التكرار'),t.isRecurring?context.l10n.recurringTask:TaskPresentation.text(context,'Not recurring','غير متكررة'))])),
  _section(context,TaskPresentation.text(context,'Progress and execution','التقدم والتنفيذ'),Column(children:[TaskProgressIndicator(t.progressPercentage),const SizedBox(height:9),_row(context,context.l10n.checklist,d.checklistSummary.total==0?TaskPresentation.text(context,'No checklist items','لا توجد عناصر في قائمة التحقق'):TaskPresentation.text(context,'${d.checklistSummary.completed} of ${d.checklistSummary.total} completed','اكتمل ${d.checklistSummary.completed} من ${d.checklistSummary.total}')),_row(context,context.l10n.subtasks,'${d.subtaskCount}'),_row(context,context.l10n.comments,'${d.commentCount}'),_row(context,context.l10n.attachments,'${d.attachmentCount}')])) ,
  if(d.activeBlocker!=null||d.approval!=null||t.syncState==LocalEntitySyncState.conflict)_section(context,TaskPresentation.text(context,'Attention','يتطلب الانتباه'),Column(children:[if(d.activeBlocker!=null)_row(context,context.l10n.blocker,TaskPresentation.text(context,'Active blocker','عائق نشط')),if(d.approval!=null)_row(context,context.l10n.approval,TaskPresentation.approval(context,d.approval!.status)),if(t.syncState==LocalEntitySyncState.conflict)_row(context,context.l10n.synchronization,TaskPresentation.sync(context,t.syncState))])),
  _section(context,context.l10n.timeline,Column(children:[for(var i=0;i<d.timeline.length;i++)_TimelineTile(entry:d.timeline[i],last:i==d.timeline.length-1)])),
  Padding(padding:const EdgeInsets.all(12),child:Row(children:[const Icon(Icons.info_outline,size:18),const SizedBox(width:8),Expanded(child:Text(TaskPresentation.text(context,'Task actions will be enabled in later workflow phases.','سيتم تفعيل إجراءات المهمة في مراحل سير العمل اللاحقة.'),style:Theme.of(context).textTheme.bodySmall))])),const SizedBox(height:16)]));}));}
 Widget _section(BuildContext c,String? title,Widget child)=>Card(child:Padding(padding:const EdgeInsets.all(12),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[if(title!=null)...[Text(title,style:Theme.of(c).textTheme.titleMedium?.copyWith(fontWeight:FontWeight.bold)),const Divider()],child])));
 Widget _row(BuildContext c,String label,String value)=>Padding(padding:const EdgeInsets.symmetric(vertical:5),child:Row(crossAxisAlignment:CrossAxisAlignment.start,children:[Expanded(flex:2,child:Text(label,style:Theme.of(c).textTheme.labelMedium)),const SizedBox(width:8),Expanded(flex:3,child:Text(value))]));
 String _date(BuildContext c,DateTime? date)=>date==null?'—':'${MaterialLocalizations.of(c).formatMediumDate(date)} · ${MaterialLocalizations.of(c).formatTimeOfDay(TimeOfDay.fromDateTime(date))}';
}
class _TimelineTile extends StatelessWidget{const _TimelineTile({required this.entry,required this.last});final TaskTimelineEntry entry;final bool last;@override Widget build(BuildContext context){final ar=Localizations.localeOf(context).languageCode=='ar';final actor=ar?entry.actor?.nameAr:entry.actor?.nameEn;return IntrinsicHeight(child:Row(crossAxisAlignment:CrossAxisAlignment.stretch,children:[SizedBox(width:34,child:Column(children:[CircleAvatar(radius:14,child:Icon(entry.eventType==AuditEventType.created?Icons.add_task:Icons.history,size:15)),if(!last)Expanded(child:Container(width:2,color:Theme.of(context).colorScheme.outlineVariant))])),const SizedBox(width:8),Expanded(child:Padding(padding:const EdgeInsets.only(bottom:13),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(TaskPresentation.event(context,entry.eventType),style:Theme.of(context).textTheme.titleSmall),if(actor!=null)Text(TaskPresentation.text(context,'By $actor','بواسطة $actor')),Text('${MaterialLocalizations.of(context).formatFullDate(entry.timestamp)} · ${MaterialLocalizations.of(context).formatTimeOfDay(TimeOfDay.fromDateTime(entry.timestamp))}',style:Theme.of(context).textTheme.bodySmall),if(entry.reason?.isNotEmpty==true)Text(entry.reason!),if(entry.offline)Row(children:[const Icon(Icons.cloud_off,size:14),const SizedBox(width:4),Text(TaskPresentation.text(context,'Recorded offline','سُجل دون اتصال'))])])))]));}}
