import 'dart:async';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import '../../../app/localization/localization_extensions.dart';
import '../../../core/widgets/foundation_views.dart';
import '../domain/task_query_models.dart';
import 'task_providers.dart';
import 'task_widgets.dart';

class TaskListPage extends ConsumerStatefulWidget { const TaskListPage({super.key}); @override ConsumerState<TaskListPage> createState()=>_TaskListPageState(); }
class _TaskListPageState extends ConsumerState<TaskListPage>{ Timer? _debounce; @override void dispose(){_debounce?.cancel();super.dispose();}
 @override Widget build(BuildContext context){final async=ref.watch(taskQueryResultProvider);final query=ref.watch(currentTaskQueryProvider);return Scaffold(appBar:AppBar(title:Text(context.l10n.myTasks)),body:SafeArea(child:Column(children:[
  Padding(padding:const EdgeInsets.all(12),child:TextField(decoration:InputDecoration(prefixIcon:const Icon(Icons.search),hintText:context.l10n.myTasks,suffixIcon:query.searchText.isEmpty?null:IconButton(icon:const Icon(Icons.clear),onPressed:()=>ref.read(currentTaskQueryProvider.notifier).state=query.copyWith(searchText:''))),onChanged:(v){_debounce?.cancel();_debounce=Timer(const Duration(milliseconds:300),()=>ref.read(currentTaskQueryProvider.notifier).state=query.copyWith(searchText:v));})),
  SizedBox(height:48,child:ListView(scrollDirection:Axis.horizontal,padding:const EdgeInsets.symmetric(horizontal:12),children:[for(final view in TaskListView.values)Padding(padding:const EdgeInsetsDirectional.only(end:6),child:ChoiceChip(label:Text(_viewLabel(view,Localizations.localeOf(context).languageCode=='ar')),selected:query.view==view,onSelected:(_)=>ref.read(currentTaskQueryProvider.notifier).state=query.copyWith(view:view)))])),
  Expanded(child:async.when(loading:()=>const Center(child:CircularProgressIndicator()),error:(e,s)=>AppErrorView(label:context.l10n.somethingWentWrong,retryLabel:context.l10n.retry,onRetry:()=>ref.invalidate(taskQueryResultProvider)),data:(result){if(result==null)return const SizedBox.shrink();if(result.items.isEmpty)return Center(child:Text(context.l10n.noData));return RefreshIndicator(onRefresh:()async=>ref.invalidate(taskQueryResultProvider),child:LayoutBuilder(builder:(context,c){final columns=c.maxWidth>=700?2:1;return GridView.builder(padding:const EdgeInsets.all(12),gridDelegate:SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount:columns,mainAxisExtent:250,crossAxisSpacing:12,mainAxisSpacing:12),itemCount:result.items.length,itemBuilder:(c,i)=>TaskCard(item:result.items[i],onTap:()=>context.push('/tasks/${result.items[i].task.id}')));}));}))])));}}

String _viewLabel(TaskListView v,bool ar)=>switch(v){TaskListView.all=>ar?'الكل':'All',TaskListView.today=>ar?'اليوم':'Today',TaskListView.thisWeek=>ar?'هذا الأسبوع':'This week',TaskListView.overdue=>ar?'متأخرة':'Overdue',TaskListView.blocked=>ar?'متعطلة':'Blocked',TaskListView.awaitingApproval=>ar?'بانتظار الموافقة':'Awaiting approval',TaskListView.teamQueue=>ar?'قائمة الفريق':'Team queue',TaskListView.completed=>ar?'مكتملة':'Completed',TaskListView.drafts=>ar?'مسودات':'Drafts'};

class TaskDetailsPage extends ConsumerWidget {const TaskDetailsPage({super.key,required this.taskId});final String taskId;
 @override Widget build(BuildContext context,WidgetRef ref){final async=ref.watch(taskDetailsProvider(taskId));return Scaffold(appBar:AppBar(title:Text(context.l10n.myTasks)),body:async.when(loading:()=>const Center(child:CircularProgressIndicator()),error:(e,s)=>AppErrorView(label:context.l10n.somethingWentWrong,retryLabel:context.l10n.retry,onRetry:()=>ref.invalidate(taskDetailsProvider(taskId))),data:(d){if(d==null)return Center(child:Text(context.l10n.accessDenied));final ar=Localizations.localeOf(context).languageCode=='ar';final t=d.task;return ListView(padding:const EdgeInsets.all(16),children:[Text(t.taskNumber),Text(ar?t.titleAr:(t.titleEn??t.titleAr),style:Theme.of(context).textTheme.headlineSmall),Wrap(spacing:6,children:[TaskStatusBadge(t.status),TaskPriorityBadge(d.priority),TaskConfidentialityBadge(d.confidentiality?.code),TaskSyncBadge(t.syncState)]),const SizedBox(height:16),Text(ar?t.descriptionAr:(t.descriptionEn??t.descriptionAr)),const Divider(),ListTile(leading:const Icon(Icons.person),title:Text((ar?d.leadOwner?.nameAr:d.leadOwner?.nameEn)??'—')),ListTile(leading:const Icon(Icons.groups),title:Text((ar?d.assignedTeam?.nameAr:d.assignedTeam?.nameEn)??'—')),ListTile(leading:const Icon(Icons.checklist),title:Text('${d.checklistSummary.completed}/${d.checklistSummary.total}')),TaskProgressIndicator(t.progressPercentage),const Divider(),for(final e in d.timeline)ListTile(leading:const Icon(Icons.history),title:Text(e.eventType.code),subtitle:Text(MaterialLocalizations.of(context).formatFullDate(e.timestamp)))]); }));}}
