import '../../../domain/app_clock.dart';
import '../app_database.dart';
import 'demo_seed_ids.dart';
class DemoDataService { DemoDataService(this.database,this.clock); final AppDatabase database; final AppClock clock; static const seedVersion=1; Future<int?> getSeedVersion() async { final row=await database.customSelect("SELECT value FROM app_settings WHERE key='demo_seed_version'").getSingleOrNull(); return int.tryParse(row?.read<String>('value')??''); }
 Future<void> ensureSeeded() async { if(await getSeedVersion()==seedVersion)return; await resetAndSeed(); }
 Future<void> resetAndSeed()=>database.transaction(() async { await database.customStatement('PRAGMA defer_foreign_keys = ON'); for(final table in const ['role_permissions','team_memberships','task_approvals','deadline_extension_requests','task_blockers','task_attachments','task_comments','checklist_items','task_assignments','audit_events','sync_operations','app_notifications','tasks','recurrence_rules','task_templates','notification_templates','escalation_rules','approval_rules','categories','priorities','confidentiality_levels','teams','users','permissions','roles','departments','organizations','saved_task_filters','app_settings']) { await database.customStatement('DELETE FROM $table'); } await _seed(); });
 Future<void> _seed() async { final now=clock.now().toUtc(); final iso=now.toIso8601String(); await database.customStatement("INSERT INTO organizations VALUES ('org-demo','منظمة العرض','Demo Organization')");
 for(final r in const [('role-employee','employee','موظف','Employee'),('role-manager','manager','مدير','Manager'),('role-senior-management','senior_management','إدارة عليا','Senior Management'),('role-administrator','administrator','مسؤول','Administrator')]) { await database.customStatement('INSERT INTO roles VALUES (?,?,?,?)',r); }
 final deps=[(DemoSeedIds.executive,'EXEC','الإدارة التنفيذية','Executive Management',null),(DemoSeedIds.operations,'OPS','إدارة العمليات','Operations Department',null),(DemoSeedIds.finance,'FIN','الإدارة المالية','Finance Department',null),(DemoSeedIds.humanResources,'HR','الموارد البشرية','Human Resources Department',null),(DemoSeedIds.informationTechnology,'IT','تقنية المعلومات','Information Technology Department',null)]; for(var i=0;i<deps.length;i++){final d=deps[i];await database.customStatement('INSERT INTO departments (id,code,name_ar,name_en,parent_department_id,manager_user_id,is_active,sort_order,created_at,updated_at) VALUES (?,?,?,?,?,NULL,1,?,?,?)',[d.$1,d.$2,d.$3,d.$4,d.$5,i,iso,iso]);}
 final users=[(DemoSeedIds.omar,'1001','عمر النعيمي','Omar Al Nuaimi',DemoSeedIds.executive,null,DemoSeedIds.roleSenior,'ON'),(DemoSeedIds.sara,'1002','سارة محمود','Sara Mahmoud',DemoSeedIds.operations,DemoSeedIds.omar,DemoSeedIds.roleManager,'SM'),(DemoSeedIds.ahmed,'1003','أحمد حسن','Ahmed Hassan',DemoSeedIds.operations,DemoSeedIds.sara,DemoSeedIds.roleEmployee,'AH'),(DemoSeedIds.laila,'1004','ليلى يوسف','Laila Youssef',DemoSeedIds.informationTechnology,DemoSeedIds.omar,DemoSeedIds.roleAdministrator,'LY'),(DemoSeedIds.khaled,'1005','خالد إبراهيم','Khaled Ibrahim',DemoSeedIds.informationTechnology,DemoSeedIds.laila,DemoSeedIds.roleEmployee,'KI')]; for(final u in users){await database.customStatement("INSERT INTO users (id,employee_number,name_ar,name_en,job_title_ar,department_id,manager_id,role_id,avatar_initials,status,is_active,created_at,updated_at) VALUES (?,?,?,?,'موظف',?,?,?,?, 'active',1,?,?)",[u.$1,u.$2,u.$3,u.$4,u.$5,u.$6,u.$7,u.$8,iso,iso]);}
 final teams=[(DemoSeedIds.fieldOperations,'FIELD',DemoSeedIds.operations,'العمليات الميدانية','Field Operations',0),(DemoSeedIds.serviceCoordination,'SERVICE',DemoSeedIds.operations,'تنسيق الخدمات','Service Coordination',0),(DemoSeedIds.accountsPayable,'AP',DemoSeedIds.finance,'الحسابات الدائنة','Accounts Payable',0),(DemoSeedIds.reporting,'REPORT',DemoSeedIds.finance,'التقارير','Reporting',0),(DemoSeedIds.recruitment,'RECRUIT',DemoSeedIds.humanResources,'التوظيف','Recruitment',0),(DemoSeedIds.employeeServices,'EMP-SVC',DemoSeedIds.humanResources,'خدمات الموظفين','Employee Services',0),(DemoSeedIds.technicalSupportQueue,'TECH-Q',DemoSeedIds.informationTechnology,'قائمة الدعم الفني','Technical Support Queue',1),(DemoSeedIds.applicationSupport,'APP-SUP',DemoSeedIds.informationTechnology,'دعم التطبيقات','Application Support',0)]; for(var i=0;i<teams.length;i++){final t=teams[i];await database.customStatement('INSERT INTO teams VALUES (?,?,?,?,?,NULL,?,1,?,?,?)',[t.$1,t.$2,t.$3,t.$4,t.$5,t.$6,i,iso,iso]);}
 for(final p in const [('priority-low','low','منخفض','Low',1),('priority-normal','normal','عادي','Normal',2),('priority-high','high','عال','High',3),('priority-urgent','urgent','عاجل','Urgent',4),('priority-critical','critical','حرج','Critical',5)]) { await database.customStatement("INSERT INTO priorities VALUES (?,?,?,?,?,'flag','standard',60,120,?,1)",[p.$1,p.$2,p.$3,p.$4,p.$5,p.$5]); }
 await database.customStatement("INSERT INTO confidentiality_levels VALUES ('confidentiality-internal','internal','داخلي','Internal',1,'standard',1,1)");
 final cats=['general_administrative','operations','finance','human_resources','information_technology','compliance','maintenance','report_preparation','review_approval','training_acknowledgement']; for(var i=0;i<cats.length;i++){await database.customStatement("INSERT INTO categories VALUES (?,?,?, ?,0,0,'priority-normal',1,1,60,1,?)",['category-${cats[i]}',cats[i],cats[i],cats[i],i]);}
 for(var i=1;i<=12;i++){ final id='user-copy-$i'; await database.customStatement("INSERT INTO users (id,employee_number,name_ar,name_en,job_title_ar,department_id,manager_id,role_id,avatar_initials,status,is_active,created_at,updated_at) VALUES (?,? ,?,?,'موظف',?,?,'role-employee','DE','active',1,?,?)",[id,'20${i.toString().padLeft(2,'0')}','موظف تجريبي $i','Demo Employee $i',i.isEven?DemoSeedIds.finance:DemoSeedIds.humanResources,DemoSeedIds.sara,iso,iso]); }
 final due=now.add(const Duration(days:7)).toIso8601String();
 Future<void> task(String id,String number,String title,{String? batch,String? team,String status='in_progress',String? recurrence})=>database.customStatement("INSERT INTO tasks (id,task_number,title_ar,title_en,description_ar,description_en,creator_id,creator_role_code,creation_source,assignment_mode,lead_owner_id,assigned_team_id,parent_task_id,batch_id,priority_id,category_id,status,confidentiality_level_id,visibility_type,due_date,progress_percentage,approval_required,completion_evidence_required,allow_decline,allow_extension,approval_status,is_personal,is_recurring,recurrence_rule_id,created_at,updated_at,local_version,sync_state,is_locally_modified,is_deleted) VALUES (?,?,?, ?,'وصف تجريبي واقعي','Realistic synthetic scenario description','user-sara-mahmoud','manager','manual',?,'user-ahmed-hassan',?,NULL,?,'priority-normal','category-operations',?,'confidentiality-internal','assigned_users',?,25,0,0,1,1,'not_required',0,?, ?,?,?,1,'synced',0,0)",[id,number,title,title,batch==null?(team==null?'single_owner':'team_queue'):'individual_copies',team,batch,status,due,recurrence==null?0:1,recurrence,iso,iso]);
 for(var i=1;i<=15;i++){ await task(DemoSeedIds.scenario(i),'SCN-${i.toString().padLeft(2,'0')}','سيناريو $i'); }
 for(var i=1;i<=12;i++){ final id='scenario-06-copy-$i'; await task(id,'SCN-06-$i','إقرار السياسة السنوية',batch:'batch-policy-annual',status:i<=4?'completed':'assigned'); await database.customStatement("INSERT INTO task_assignments (id,task_id,user_id,assignment_role,assignment_status,is_primary,assigned_at,created_at,updated_at) VALUES (?,?,?,?,?,1,?,?,?)",['assignment-copy-$i',id,'user-copy-$i','owner',i<=4?'completed':'assigned',iso,iso,iso]); }
 await task('scenario-07-unclaimed','SCN-07-U','طلب دعم غير مطالب',team:DemoSeedIds.technicalSupportQueue,status:'assigned'); await task('scenario-07-claimed','SCN-07-C','طلب دعم مطالب',team:DemoSeedIds.technicalSupportQueue);
 await database.customStatement("INSERT INTO task_assignments (id,task_id,user_id,assignment_role,assignment_status,is_primary,assigned_at,created_at,updated_at) VALUES ('assignment-queue-claimed','scenario-07-claimed','user-khaled-ibrahim','queue_claimant','active',1,?,?,?)",[iso,iso,iso]);
 await database.customStatement("INSERT INTO audit_events VALUES ('audit-reassignment','scenario-08','task','scenario-08','reassigned','user-sara-mahmoud',?,NULL,NULL,'Operational coverage','demo-device',0,'synced')",[iso]);
 await database.customStatement("INSERT INTO sync_operations VALUES ('sync-offline','task','scenario-12','update','{}',?,NULL,0,'pending',NULL,'none')",[iso]); await database.customStatement("INSERT INTO sync_operations VALUES ('sync-conflict','task','scenario-13','update','{}',?,NULL,1,'conflict','Assignment changed','assignment')",[iso]);
 await database.customStatement("INSERT INTO app_settings VALUES ('demo_seed_version','$seedVersion',?)",[iso]); }
}
}
