import '../../../domain/app_clock.dart';
import '../app_database.dart';
import 'demo_seed_ids.dart';
class DemoDataService { DemoDataService(this.database,this.clock); final AppDatabase database; final AppClock clock; static const seedVersion=1; Future<int?> getSeedVersion() async { final row=await database.customSelect("SELECT value FROM app_settings WHERE key='demo_seed_version'").getSingleOrNull(); return int.tryParse(row?.read<String>('value')??''); }
 Future<void> ensureSeeded() async { if(await getSeedVersion()==seedVersion)return; await resetAndSeed(); }
 Future<void> resetAndSeed()=>database.transaction(() async { await database.customStatement('PRAGMA defer_foreign_keys = ON'); for(final table in const ['role_permissions','team_memberships','task_approvals','deadline_extension_requests','task_blockers','task_attachments','task_comments','checklist_items','task_assignments','audit_events','sync_operations','app_notifications','tasks','recurrence_rules','task_templates','notification_templates','escalation_rules','approval_rules','categories','priorities','confidentiality_levels','teams','users','permissions','roles','departments','organizations','saved_task_filters','app_settings']) { await database.customStatement('DELETE FROM $table'); } await _seed(); });
 Future<void> _seed() async { final now=clock.now().toUtc(); final iso=now.toIso8601String(); await database.customStatement("INSERT INTO organizations VALUES ('org-demo','منظمة العرض','Demo Organization')");
 for(final r in const [('role-employee','employee','موظف','Employee'),('role-manager','manager','مدير','Manager'),('role-senior-management','senior_management','إدارة عليا','Senior Management'),('role-administrator','administrator','مسؤول','Administrator')]) { await database.customStatement('INSERT INTO roles VALUES (?,?,?,?)',r); }
 final deps=[(DemoSeedIds.executive,'EXEC','الإدارة التنفيذية','Executive Management',null),(DemoSeedIds.operations,'OPS','إدارة العمليات','Operations Department',null),(DemoSeedIds.finance,'FIN','الإدارة المالية','Finance Department',null),(DemoSeedIds.humanResources,'HR','الموارد البشرية','Human Resources Department',null),(DemoSeedIds.informationTechnology,'IT','تقنية المعلومات','Information Technology Department',null)]; for(var i=0;i<deps.length;i++){final d=deps[i];await database.customStatement('INSERT INTO departments (id,code,name_ar,name_en,parent_department_id,manager_user_id,is_active,sort_order,created_at,updated_at) VALUES (?,?,?,?,?,NULL,1,?,?,?)',[d.$1,d.$2,d.$3,d.$4,d.$5,i,iso,iso]);}
 final users=[(DemoSeedIds.omar,'1001','عمر النعيمي','Omar Al Nuaimi',DemoSeedIds.executive,null,DemoSeedIds.roleSenior,'ON'),(DemoSeedIds.sara,'1002','سارة محمود','Sara Mahmoud',DemoSeedIds.operations,DemoSeedIds.omar,DemoSeedIds.roleManager,'SM'),(DemoSeedIds.ahmed,'1003','أحمد حسن','Ahmed Hassan',DemoSeedIds.operations,DemoSeedIds.sara,DemoSeedIds.roleEmployee,'AH'),(DemoSeedIds.laila,'1004','ليلى يوسف','Laila Youssef',DemoSeedIds.informationTechnology,DemoSeedIds.omar,DemoSeedIds.roleAdministrator,'LY'),(DemoSeedIds.khaled,'1005','خالد إبراهيم','Khaled Ibrahim',DemoSeedIds.informationTechnology,DemoSeedIds.laila,DemoSeedIds.roleEmployee,'KI')]; for(final u in users){await database.customStatement("INSERT INTO users (id,employee_number,name_ar,name_en,job_title_ar,department_id,manager_id,role_id,avatar_initials,status,is_active,created_at,updated_at) VALUES (?,?,?,?,'موظف',?,?,?,?, 'active',1,?,?)",[u.$1,u.$2,u.$3,u.$4,u.$5,u.$6,u.$7,u.$8,iso,iso]);}
 final teams=[(DemoSeedIds.fieldOperations,'FIELD',DemoSeedIds.operations,'العمليات الميدانية','Field Operations',0),(DemoSeedIds.serviceCoordination,'SERVICE',DemoSeedIds.operations,'تنسيق الخدمات','Service Coordination',0),(DemoSeedIds.accountsPayable,'AP',DemoSeedIds.finance,'الحسابات الدائنة','Accounts Payable',0),(DemoSeedIds.reporting,'REPORT',DemoSeedIds.finance,'التقارير','Reporting',0),(DemoSeedIds.recruitment,'RECRUIT',DemoSeedIds.humanResources,'التوظيف','Recruitment',0),(DemoSeedIds.employeeServices,'EMP-SVC',DemoSeedIds.humanResources,'خدمات الموظفين','Employee Services',0),(DemoSeedIds.technicalSupportQueue,'TECH-Q',DemoSeedIds.informationTechnology,'قائمة الدعم الفني','Technical Support Queue',1),(DemoSeedIds.applicationSupport,'APP-SUP',DemoSeedIds.informationTechnology,'دعم التطبيقات','Application Support',0)]; for(var i=0;i<teams.length;i++){final t=teams[i];await database.customStatement('INSERT INTO teams VALUES (?,?,?,?,?,NULL,?,1,?,?,?)',[t.$1,t.$2,t.$3,t.$4,t.$5,t.$6,i,iso,iso]);}
 for(final p in const [('priority-low','low','منخفض','Low',1),('priority-normal','normal','عادي','Normal',2),('priority-high','high','عال','High',3),('priority-urgent','urgent','عاجل','Urgent',4),('priority-critical','critical','حرج','Critical',5)]) { await database.customStatement("INSERT INTO priorities VALUES (?,?,?,?,?,'flag','standard',60,120,?,1)",[p.$1,p.$2,p.$3,p.$4,p.$5,p.$5]); }
 await database.customStatement("INSERT INTO confidentiality_levels VALUES ('confidentiality-internal','internal','داخلي','Internal',1,'standard',1,1)");
 final cats=['general_administrative','operations','finance','human_resources','information_technology','compliance','maintenance','report_preparation','review_approval','training_acknowledgement']; for(var i=0;i<cats.length;i++){await database.customStatement("INSERT INTO categories VALUES (?,?,?, ?,0,0,'priority-normal',1,1,60,1,?)",['category-${cats[i]}',cats[i],cats[i],cats[i],i]);}
 for(var i=1;i<=12;i++){ final id='user-copy-$i'; await database.customStatement("INSERT INTO users (id,employee_number,name_ar,name_en,job_title_ar,department_id,manager_id,role_id,avatar_initials,status,is_active,created_at,updated_at) VALUES (?,? ,?,?,'موظف',?,?,'role-employee','DE','active',1,?,?)",[id,'20${i.toString().padLeft(2,'0')}','موظف تجريبي $i','Demo Employee $i',i.isEven?DemoSeedIds.finance:DemoSeedIds.humanResources,DemoSeedIds.sara,iso,iso]); }
 final due=now.add(const Duration(days:7)).toIso8601String();
 Future<void> task(String id,String number,String title,{String? batch,String? team,String status='in_progress',String? recurrence})=>database.customStatement("INSERT INTO tasks (id,task_number,title_ar,title_en,description_ar,description_en,creator_id,creator_role_code,creation_source,assignment_mode,lead_owner_id,assigned_team_id,parent_task_id,batch_id,priority_id,category_id,status,confidentiality_level_id,visibility_type,due_date,progress_percentage,approval_required,completion_evidence_required,allow_decline,allow_extension,approval_status,is_personal,is_recurring,recurrence_rule_id,created_at,updated_at,local_version,sync_state,is_locally_modified,is_deleted) VALUES (?,?,?, ?,'وصف تجريبي واقعي','Realistic synthetic scenario description','user-sara-mahmoud','manager','manual',?,'user-ahmed-hassan',?,NULL,?,'priority-normal','category-operations',?,'confidentiality-internal','assigned_users',?,25,0,0,1,1,'not_required',0,?, ?,?,?,1,'synced',0,0)",[id,number,title,title,batch==null?(team==null?'single_owner':'team_queue'):'individual_copies',team,batch,status,due,recurrence==null?0:1,recurrence,iso,iso]);
 for(var i=1;i<=15;i++){ await task(DemoSeedIds.scenario(i),'SCN-${i.toString().padLeft(2,'0')}','سيناريو $i'); }
 for(var i=1;i<=12;i++){ final id='scenario-06-copy-$i'; await task(id,'SCN-06-$i','إقرار السياسة السنوية',batch:'batch-policy-annual',status:i<=4?'completed':'assigned'); await database.customStatement("INSERT INTO task_assignments (id,task_id,user_id,assignment_role,assignment_status,is_primary,assigned_at,created_at,updated_at) VALUES (?,?,?,?,?,1,?,?,?)",['assignment-copy-$i',id,'user-copy-$i','owner',i<=4?'completed':'assigned',iso,iso,iso]); }
 await task('scenario-07-unclaimed','SCN-07-U','طلب دعم غير مطالب',team:DemoSeedIds.technicalSupportQueue,status:'assigned'); await task('scenario-07-claimed','SCN-07-C','طلب دعم مطالب',team:DemoSeedIds.technicalSupportQueue);
 await database.customStatement("INSERT INTO task_assignments (id,task_id,user_id,assignment_role,assignment_status,is_primary,assigned_at,created_at,updated_at) VALUES ('assignment-queue-claimed','scenario-07-claimed','user-khaled-ibrahim','queue_claimant','active',1,?,?,?)",[iso,iso,iso]);
 await database.customStatement("INSERT INTO audit_events VALUES ('audit-reassignment','scenario-08','task','scenario-08','reassigned','user-sara-mahmoud',?,NULL,NULL,'Operational coverage','demo-device',0,'synced')",[iso]);
 await database.customStatement("INSERT INTO sync_operations VALUES ('sync-offline','task','scenario-12','update','{}',?,NULL,0,'pending',NULL,'none')",[iso]); await database.customStatement("INSERT INTO sync_operations VALUES ('sync-conflict','task','scenario-13','update','{}',?,NULL,1,'conflict','Assignment changed','assignment')",[iso]);
 // Complete Phase 02 configuration and relationships.
 for(final c in const [('confidentiality-public','public','عام','Public',0),('confidentiality-confidential','confidential','سري','Confidential',2),('confidentiality-restricted','restricted','مقيد','Restricted',3)]) { await database.customStatement("INSERT INTO confidentiality_levels VALUES (?,?,?,?,?,'standard',1,?)",[c.$1,c.$2,c.$3,c.$4,c.$5,c.$5]); }
 for(final p in const [('permission-view','view_tasks'),('permission-manage','manage_tasks'),('permission-approve','approve_tasks'),('permission-reports','view_reports'),('permission-admin','administer_system')]) { await database.customStatement('INSERT INTO permissions VALUES (?,?)',[p.$1,p.$2]); }
 var rp=0; for(final role in const [DemoSeedIds.roleEmployee,DemoSeedIds.roleManager,DemoSeedIds.roleSenior,DemoSeedIds.roleAdministrator]) { for(final permission in const ['permission-view','permission-manage','permission-approve','permission-reports','permission-admin']) { if(role==DemoSeedIds.roleEmployee&&permission!='permission-view') continue; await database.customStatement('INSERT INTO role_permissions VALUES (?,?,?)',['role-permission-${rp++}',role,permission]); } }
 final memberships=[(DemoSeedIds.fieldOperations,DemoSeedIds.ahmed,'member'),(DemoSeedIds.fieldOperations,DemoSeedIds.sara,'lead'),(DemoSeedIds.technicalSupportQueue,DemoSeedIds.khaled,'queue_member')]; for(var i=0;i<memberships.length;i++){final m=memberships[i];await database.customStatement('INSERT INTO team_memberships VALUES (?,?,?,?,1,?,NULL)',['membership-$i',m.$1,m.$2,m.$3,iso]);}
 for(var i=1;i<=12;i++){await database.customStatement('INSERT INTO team_memberships VALUES (?,?,?,?,1,?,NULL)',['membership-copy-$i',i.isEven?DemoSeedIds.accountsPayable:DemoSeedIds.employeeServices,'user-copy-$i','member',iso]);}
 await database.customStatement("INSERT INTO approval_rules VALUES ('approval-evidence','evidence-approval','اعتماد الدليل','Evidence approval','category-review_approval',3,2,1,'manager',1,1)");
 await database.customStatement("INSERT INTO escalation_rules VALUES ('escalation-overdue','overdue-manager','تصعيد التأخير','Overdue manager',NULL,'priority-high',60,30,'manager','escalation',1)");
 for(final n in const [('notification-assigned','مهمة جديدة','Task assigned','تم إسناد مهمة','A task was assigned'),('notification-approval','طلب اعتماد','Approval requested','يوجد طلب اعتماد','Approval is requested'),('notification-overdue','مهمة متأخرة','Task overdue','تأخرت المهمة','A task is overdue')]) { await database.customStatement('INSERT INTO notification_templates VALUES (?,?,?,?,?,?,1)',n); }
 for(var i=1;i<=3;i++){await database.customStatement("INSERT INTO task_templates (id,title_ar,title_en,description_ar,category_id,priority_id,default_effort_minutes,approval_required,evidence_required,is_active) VALUES (?,?,?,'قالب تجريبي','category-operations','priority-normal',60,0,0,1)",['template-$i','قالب $i','Template $i']);}
 // Core assignments make every primary scenario queryable by its accountable owner.
 for(var i=1;i<=15;i++){await database.customStatement("INSERT INTO task_assignments (id,task_id,user_id,assignment_role,assignment_status,is_primary,assigned_at,created_at,updated_at) VALUES (?,?,?,?,?,1,?,?,?)",['assignment-scenario-$i',DemoSeedIds.scenario(i),DemoSeedIds.ahmed,i==5?'lead_owner':'owner',i==3?'active':'assigned',iso,iso,iso]);}
 await database.customStatement("INSERT INTO checklist_items VALUES ('check-01-a','scenario-01','التحقق من الطلب','Verify request',1,1,'user-ahmed-hassan',?,1,?,?)",[iso,iso,iso]);
 await database.customStatement("INSERT INTO checklist_items VALUES ('check-01-b','scenario-01','إغلاق الطلب','Close request',1,0,NULL,NULL,2,?,?)",[iso,iso]);
 await database.customStatement("INSERT INTO task_approvals VALUES ('approval-02','scenario-02','user-sara-mahmoud','pending',?,NULL,NULL,1)",[iso]);
 await database.customStatement("INSERT INTO task_approvals VALUES ('approval-03','scenario-03','user-sara-mahmoud','returned',?,?,'يلزم تصحيح الدليل',1)",[iso,iso]);
 await database.customStatement("UPDATE tasks SET status='returned_for_correction',approval_required=1,approval_status='returned' WHERE id='scenario-03'");
 await database.customStatement("INSERT INTO task_blockers VALUES ('blocker-04','scenario-04','user-ahmed-hassan','external_dependency','انتظار اعتماد مالي','External finance vendor',?,NULL,NULL,'active')",[now.subtract(const Duration(days:4)).toIso8601String()]);
 await database.customStatement("UPDATE tasks SET status='blocked' WHERE id='scenario-04'");
 await database.customStatement("INSERT INTO task_comments VALUES ('comment-04','scenario-04','user-ahmed-hassan','بانتظار الطرف الخارجي',?,?,0,NULL,'[]',0,'synced')",[iso,iso]);
 await database.customStatement("INSERT INTO task_assignments (id,task_id,user_id,assignment_role,assignment_status,is_primary,assigned_at,contribution_percentage,created_at,updated_at) VALUES ('assignment-05-fin','scenario-05','user-copy-2','contributor','active',0,?,40,?,?),('assignment-05-hr','scenario-05','user-copy-1','contributor','active',0,?,30,?,?)",[iso,iso,iso,iso,iso,iso]);
 await database.customStatement("INSERT INTO audit_events VALUES ('audit-queue-claim','scenario-07-claimed','task','scenario-07-claimed','assigned','user-khaled-ibrahim',?,NULL,NULL,'Queue claim','demo-device',0,'synced')",[iso]);
 await database.customStatement("INSERT INTO deadline_extension_requests VALUES ('extension-09','scenario-09','user-ahmed-hassan',?,?,?,'pending','user-sara-mahmoud',NULL,NULL)",[due,now.add(const Duration(days:14)).toIso8601String(),'External dependency requires more time']);
 await database.customStatement("INSERT INTO recurrence_rules VALUES ('recurrence-monthly','monthly',1,NULL,1,0,?,'after_occurrences',NULL,3,0,'user-sara-mahmoud',?,?)",[iso,iso,iso]);
 for(final o in const [('completed','scenario-10-completed',-30),('in_progress','scenario-10-active',0),('upcoming','scenario-10-upcoming',30)]){await task(o.$2,'${o.$2}-N','مراجعة شهرية',status:o.$1,recurrence:'recurrence-monthly');await database.customStatement("UPDATE tasks SET recurrence_source_task_id='scenario-10' WHERE id=?",[o.$2]);}
 await database.customStatement("UPDATE tasks SET confidentiality_level_id='confidentiality-restricted',visibility_type='restricted' WHERE id='scenario-11'");
 await database.customStatement("UPDATE tasks SET is_locally_modified=1,sync_state='pending',local_version=3,server_version=2 WHERE id='scenario-12'");
 await database.customStatement("UPDATE tasks SET is_locally_modified=1,sync_state='conflict',local_version=5,server_version=4 WHERE id='scenario-13'");
 await database.customStatement("UPDATE tasks SET creation_source='ai_draft',status='draft',description_ar='مدخل المستخدم: إعداد خطة زيارة؛ المقترح: تنسيق زيارة ميدانية' WHERE id='scenario-14'");
 await database.customStatement("INSERT INTO audit_events VALUES ('audit-01','scenario-01','task','scenario-01','status_changed','user-ahmed-hassan',?,NULL,NULL,'Started work','demo-device',0,'synced'),('audit-03','scenario-03','task','scenario-03','returned','user-sara-mahmoud',?,NULL,NULL,'Correction required','demo-device',0,'synced'),('audit-offline','scenario-12','task','scenario-12','updated','user-ahmed-hassan',?,NULL,NULL,'Offline progress update','demo-device',1,'pending')",[iso,iso,iso]);
 await database.customStatement("INSERT INTO app_notifications VALUES ('notification-demo','user-ahmed-hassan','task_assigned','مهمة جديدة','Task assigned','لديك مهمة','You have a task','scenario-01',?,NULL,0,'in_app','delivered')",[iso]);
 await database.customStatement("INSERT INTO app_settings VALUES ('demo_seed_version','$seedVersion',?)",[iso]); }
}
}
